release:
	mkdir -p _output
	GOOS=windows GOARCH=amd64 go build -o _output/windows/amd64/app.exe ./app/...
	GOOS=linux GOARCH=amd64   go build -o _output/linux/amd64/app       ./app/...
	GOOS=linux GOARCH=arm     go build -o _output/linux/arm/app         ./app/...
	GOOS=linux GOARCH=arm64   go build -o _output/linux/arm64/app       ./app/...
	GOOS=linux GOARCH=ppc64   go build -o _output/linux/ppc64/app       ./app/...
	GOOS=linux GOARCH=s390x   go build -o _output/linux/s390x/app       ./app/...
