name: k8s-create-release
on:
  repository_dispatch:
    types: dispatch-k8s-create-release
jobs:
  k8s-create-release:
    runs-on: ubuntu-18.04
    steps:
    - run: |
        git version
        cd /home/runner/work/kubeadm-test/kubeadm-test
        rm -rf ./*
        git clone https://github.com/${{ github.repository }} ./
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.6'
    - run: |
        export RELEASE_TAG=${{ github.event.client_payload.release_tag }}
        export TOKEN=${{ secrets.GITHUB_TOKEN }}
        export DEST=${{ github.repository }}
        ./hack/ci-release.sh
