name: k8s-repo-sync
on:
  repository_dispatch:
    types: manual_trigger_repo_sync
  schedule:
    - cron: '*/5 * * * *'
jobs:
  k8s-repo-sync:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.9.3'
    - run: |
        cd ./k8s-repo-tools/
        go build ./cmd/k8s-repo-sync
        ./k8s-repo-sync \
          --dest=neolit123/kubeadm-test \
          --source=kubernetes/kubernetes \
          --token=${{secrets.GITHUB_TOKEN}} \
          --min-version=v1.18.0-alpha.3 \
          --dry-run=false \
          --force=true
