name: k8s-repo-sync
on:
  repository_dispatch:
    types: dispatch-k8s-repo-sync
  schedule:
    - cron: '0 11 * * *'
jobs:
  k8s-repo-sync:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.6'
    - run: |
        cd ./k8s-repo-tools/
        go run ./cmd/k8s-repo-sync \
          --source=kubernetes/kubernetes \
          --dest=${{ github.repository }} \
          --token=${{ secrets.GITHUB_TOKEN }} \
          --min-version=v1.18.0-alpha.3 \
          --dry-run=false \
          --force=true \
          --output=./output.json
    - uses: actions/upload-artifact@v1
      with:
        name: output.json
        path: ./k8s-repo-tools/output.json
    - run: |
        export TOKEN=${{ secrets.RELEASE_TOKEN }}
        export DEST=${{ github.repository }}
        export SYNC_OUTPUT=./k8s-repo-tools/output.json
        ./hack/ci-dispatch-release.sh
