name: k8s-create-release
on:
  repository_dispatch:
    types: dispatch-k8s-create-release
  create:
    tags:
    - '*'
jobs:
  k8s-create-release:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
        fetch-depth: '0'
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.6'
    - run: |
        RELEASE_TAG=$GITHUB_REF TOKEN=${{ secrets.GITHUB_TOKEN }} DEST=${{ github.repository }} ./hack/ci-release.sh
