name: tag-created
on:
  repository_dispatch:
    types: dispatch-k8s-create-release
  create:
    tags:
    - '*'
jobs:
  tag-created:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.6'
    - run: |
        TOKEN=${{ secrets.GITHUB_TOKEN }} RELEASE_TAG=$GITHUB_REF DEST=neolit123/kubeadm-test ./hack/ci-release.sh
