name: k8s-repo-ff
on:
  repository_dispatch:
    types: manual_trigger_repo_ff
  schedule:
    - cron: '0 11 * * *'
jobs:
  k8s-repo-ff:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.6'
    - run: |
        cd ./k8s-repo-tools        
        go run ./cmd/k8s-repo-ff \
          --dest=neolit123/kubeadm-test \
          --token=${{secrets.GITHUB_TOKEN}} \
          --dry-run=false \
          --force=true
