name: tag-created
on:
  create:
    tags:
    - '*'
jobs:
  tag-created:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.6'
    - run: |
        echo "${{ env.GITHUB_SHA }} ${{ env.GITHUB_REF }}"
