on: issue_comment
name: handle the /support command
jobs:
  support_comment:
    runs-on: ubuntu-20.04
    if: |
      github.event_name == 'issue_comment'
      && github.event.action == 'created'
      && contains(github.event.comment.body, '/support')
    steps:
      - name: comment with support text
        if: steps.command.outputs.command-name
        uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Hello, @${{ github.event.issue.user.login }} :robot: :wave:

            You seem to have troubles using Kubernetes and kubeadm.
            Note that our issue trackers **should not** be used for providing support to users.
            There are special channels for that purpose.

            Please see:
            - https://github.com/kubernetes/kubeadm#support
      - name: add support label
        if: steps.command.outputs.command-name
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: kind/support
      - name: close issue
        if: steps.command.outputs.command-name
        uses: peter-evans/close-issue@v1
